# Project1 
float64 model_r1
float64 vy_est1
float64 eso1_total
float64 eso1_pure
float64 Cf_est
float64 Cr_est
float64 eso1_x

# Project2
float64 model_r2
float64 vy_est2
float64 gamma_angle
float64 r_t
float64 eso2_total
float64 Cf_est2
float64 Cr_est2
float64 Ct_est2

float64 kappa
float64 r_ref
float64 theta
float64 vy_model

# Common for both projects
float64 ay_slope_compensation
float64 iter_time