uint8 flag       # 比赛状态标志位
uint8 RED = 0    # 红色旗帜：紧急停止
uint8 GREEN = 1  # 绿色旗帜：正常运行且没有限速
uint8 BLACK = 2  # 黑色旗帜：比赛完成，紧急停止
uint8 G5 = 5     # 绿色旗帜且限速5km/h
uint8 G10 = 10   # 绿色旗帜且限速10km/h
uint8 G15 = 15   # 绿色旗帜且限速15km/h
uint8 G20 = 20   # 绿色旗帜且限速20km/h
uint8 G25 = 25   # 绿色旗帜且限速25km/h
uint8 G30 = 30   # 绿色旗帜且限速30km/h
uint8 G35 = 35   # 绿色旗帜且限速35km/h
uint8 G40 = 40   # 绿色旗帜且限速40km/h
uint8 G45 = 45   # 绿色旗帜且限速45km/h
uint8 G50 = 50   # 绿色旗帜且限速50km/h
uint8 G55 = 55   # 绿色旗帜且限速55km/h
uint8 G60 = 60   # 绿色旗帜且限速60km/h 
uint8 G80 = 80   # 绿色旗帜且限速80km/h
