pid_controller:
  kp: 0.6
  ki: 0.05
  kd: 0.1
  max_throttle: 0.8
  max_brake: 0.8
  integral_limit: 2.0
  speed_tolerance: 0.2
  min_target_speed: 0.5


pure_pursuit:
  wheelbase: 1.8
  max_steering_angle: 0.40
  min_path_points: 3.0
  min_lookahead_distance: 5.0
  lookahead_speed_coeff: 0.6
