imu_topic: /carla/ego_vehicle/imu # 输入的IMU话题
ltr_topic: /race/ltr # 输出的LTR话题
frame_id: ego_vehicle # 车辆坐标系

# 悬架参数
suspension_stiffness: 15.0 # 基础悬架刚度，单位：N/m
damping_coefficient: 5.0   # 基础阻尼系数，单位：N/(m/s)
suspension_nonlinearity: 0.01  # 悬架非线性系数（越大非线性越强）
damping_nonlinearity: 0.01     # 阻尼非线性系数（越大非线性越强）

# 质量参数
sprung_mass: 25.0       # 簧载质量，单位：千克（车身等由悬架支撑的质量）
unsprung_mass: 2.0      # 簧下质量，单位：千克（车轮、轮毂等非悬架支撑的质量）
cg_height_sprung: 0.5    # 簧载质量重心高度，单位：米
cg_height_unsprung: 0.1   # 簧下质量重心高度，单位：米

# 其他车辆参数
track_width: 0.15          # 轮距，单位：米
gravity: 9.806             # 重力加速度，单位：m/s²

