uint16 	GpsWeek		#GPS周	
float32 GpsWeekSecond	#GPS周内秒
float32 InsLatErr	#纬度误差
float32 InsLonErr	#经度误差
float32 InsAltErr	#高度误差
uint8 InsLatConf	#纬度置信度
uint8 InsLonConf	#经度置信度
uint8 InsAltConf	#高度置信度
float32 InsHeadingErr	#航向角误差
float32 InsPitchErr	#俯仰角误差
float32 InsRollErr	#横滚角误差
uint8 InsHeadingConf	#航向角置信度
uint8 InsPitchConf	#俯仰角置信度
uint8 InsRollConf	#横滚角置信度
float32 InsVelNErr	#北向速度误差
float32 InsVelEErr	#东向速度误差
float32 InsVelDErr	#地向速度误差
uint8 InsVelNConf	#北向速度置信度
uint8 InsVelEConf	#东向速度置信度
uint8 InsVelDConf	#地向速度置信度
uint8 InsCaliProg     #标定进度
uint8 cycle_cnt_cov	#循环计数


