geometry_msgs/Pose cur_pose
uint8 direction

float32 close
float32 remote
float32 front
float32 back
float32 low
float32 high
---
uint8 ret_code
bool is_empty

uint8 DirectionLeft  = 0
uint8 DirectinoRight = 1

uint8 RetSuccess       = 0
uint8 RetError         = 1
uint8 ParameterInvalid = 2
