Header header

uint8 BrakeEnableStatusDisable = 0
uint8 BrakeEnableStatusEnable  = 1
uint8 brake_enable_status

uint8 BrakeLampStatusOff = 0
uint8 BrakeLampStatusOn  = 1
uint8 brake_lamp_status

uint8 EpbStatusRelease   = 0
uint8 EpbStatusBrake     = 1
uint8 EpbStatusReleasing = 2
uint8 EpbStatusBraking   = 3
uint8 epb_status

float32 brake_pedal
uint8   aeb_enable_status
uint8   aeb_trigger_status
float32 brake_pressure
