Header header

uint8 LampStatusOff = 0
uint8 LampStatusOn = 1
uint8 pos_lamp_status
uint8 head_lamp_status
uint8 left_lamp_status
uint8 right_lamp_status
uint8 high_beam_status
uint8 fog_lamp_status
uint8 hazard_war_lamp_status
uint8 body_lamp_status
uint8 read_lamp_status

uint8 DoorStatusInvalid      = 0
uint8 DoorStatusOpening      = 1
uint8 DoorStatusClosing      = 2
uint8 DoorStatusOpenInplace  = 3
uint8 DoorStatusCloseInplace = 4
uint8 DoorStatusOpenTimeout  = 5
uint8 DoorStatusCloseTimeout = 6
uint8 door_status

uint8 WipersStatusOff  = 0
uint8 WipersStatusLow  = 1
uint8 WipersStatusMid  = 2
uint8 WipersStatusHigh = 3
uint8 wipers_status

uint8 SafetyBeltStatusNo         = 0
uint8 SafetyBeltStatusSit        = 1
uint8 SafetyBeltStatusSafetybelt = 2
uint8 SafetyBeltStatusUnknow     = 3
uint8 safety_belt1
uint8 safety_belt2
uint8 safety_belt3
uint8 safety_belt4